### ISSUE TITLE
It doesn't fucking work

### ISSUE THREAD

**Issue by ajvpot** [ByteMail/ByteMail#2] opened 2013-06-20 01:45 UTC
```
ByteMail$ send
To: a01ab3df05f64bf4ba0b18044162d7f0
Title: hi
Message: you're gay.
Generating antispam on average difficulty (5)
Sending message ID 290e6655999b447ebc424af812a7569d with key PJUQC8xhHm8cksQjLrw
FyJFFurUpIsfCdyF6DYpZs/4ma6YznxIlxOsHCXkX66uis3G2I7Ogri2zt3xgS14hTU3njyfhJLdXq1B
KMyzmQyVTFeFW5eww/v7w0QhU4EJEeIEuZXn3TVM5p0+DU5BDE3W0WUWeDFdp6zvLxlQYUww=
Message Sent!
ByteMail$
To:
Traceback (most recent call last):
  File "bytemail.py", line 228, in <module>
    c.cmdloop()
  File "C:\Python27\lib\cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "C:\Python27\lib\cmd.py", line 208, in onecmd
    return self.emptyline()
  File "C:\Python27\lib\cmd.py", line 231, in emptyline
    return self.onecmd(self.lastcmd)
  File "C:\Python27\lib\cmd.py", line 221, in onecmd
    return func(arg)
  File "bytemail.py", line 147, in do_send
    if len(str(addressbook.check_entry(to))) != 32:
  File "F:\Development\ByteMail\addressbook.py", line 5, in check_entry
    for x in ourdb:
TypeError: 'bool' object is not iterable
```

**Comment by f-prime** [comment] 2013-06-20 01:47
Lol, I got your message. I'll fix that error though... it's annoying

**Comment by f-prime** [comment] 2013-06-20 02:02
It's fixed, redownload please.

**Comment by twilightsparklehf** [comment] 2013-06-20 02:34
This one was my fault, it has to do with the address book code. Sorry, I should have added error checking on that. Max fixed it for me because He's awesome :+1: I think it's safe to close this now.

**Comment by twilightsparklehf** [comment] 2013-06-21 01:57
Reopening - not fixed. I'm assigning this issue to myself for fixing, expect a patch within 24 hours.

**Comment by f-prime** [comment] 2013-06-21 02:02
I haven't gotten the error at all since the patch.

**Comment by twilightsparklehf** [comment] 2013-06-21 16:10
Confirmed fixed on a fresh install - I just failed while updating the copy I first tested with.

**Closed as completed by twilightsparklehf** 2013-06-21 16:10 UTC
Labels: bug
